### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by SuperAdam47** [SavionLegends/Grenade#1]
Can not fires

**Comment by SavionLegends** [comment]
Please explain what you mean by "fire"

**Comment by SuperAdam47** [comment]
Can not exploded

**Comment by SuperAdam47** [comment]
ahh.ss

**Comment by SuperAdam47** [comment]
primed tnt egg droping

**Comment by SuperAdam47** [comment]
[Proof Video in The Bugs](https://youtu.be/2rHfh1XqChU)
